[project]
name = "music-analysis-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mohanroda12", email = "mohanroda12@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "python-dotenv>=1.2.3",
    "uvicorn[standard]>=0.52.3",
]

[tool.uv]
package = false
